spring:
  r2dbc:
#    url: r2dbc:oracle:thin:@localhost:1521:xe
    url: r2dbc:pool:oracle://localhost:1521:xe
    username: system
    password: oracle

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
