logging:
  level:
    org.springframework.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/beer?initialSize=1&maxIdleTime=PT60S
    username: postgres
    password: 1234
  application:
    name: beer-webflux

server:
  port: 8081

client:
  file-upload:
    url: http://localhost:8082